-- Import Lua modules
require('core/autocmds')
require('core/keymaps')
require('core/lazy')
require('core/options')
require('plugins/catppuccin')
require('plugins/gitsigns')
-- require('plugins/nvim-cmp')
-- require('plugins/nvim-lspconfig')
require('plugins/lsp-zero')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/which-key')
