-- Import Lua modules
require('core/autocmds')
require('core/lazy')
require('core/options')
require('plugins/catppuccin')
require('plugins/gitsigns')
require('plugins/lsp-zero')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/which-key')
require('plugins/comment')
require('core/keymaps')